### ISSUE TITLE
Images in XD NOT Marked for Export still imported

### ISSUE THREAD

**Issue by byteasc** [Supernova-Studio/public-issue-tracker#135]
### Issue
> 	If images are marked in Adobe XD to not be exported they're still loaded on Import in Supernova

### Context
> 	

### Expected result
> 	​I would expect that if something is not marked for export that it would also not be imported into Supernova Studio

### Current result
> 	Images are imported and have to be manually deleted otherwise they'll also export out to whatever framework is being used

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by jan-supernova** [comment]
Hey byteasc,
     Thank you very much for your report. We have been able to simulate the issue in the latest version of Supernova Studio and we are working hard on fixing it as soon as possible. We will let you know when the issue is resolved. Thank you again for your report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey byteasc,
This is the correct behaviour - using export slices is discouraged due to the way how our inference engine in Supernova Studio works. Supernova Studio doesn't have design layers or editable paths, which means that those would be missing from the designs altogether, which would be wrong. This is the reason why we import all assets. We hope this answer clears up everything for you.

Have a wonderful day!
Jan, Supernova Team
