### ISSUE TITLE
all components disappeared  when i use ScrollView (flutter)

### ISSUE THREAD

**Issue by badr131** [Supernova-Studio/public-issue-tracker#136]
### Issue
> 	component disappear when i use ScrollView and two component are on the same vertical line 

### Context
> 	when two components are on the same line it generate positions tag to the code in flutter and it break the  result 
when one component is alone on the same line direction scrollview work fine without an issue 

### Expected result
> 	all the component should be appearing 

### Current result
> 	all component inside scrollview disappeared 

### Possible fix
> 	 no idea 

### Screenshots
> 	 [video](https://streamable.com/gxqby)

-------------------------------------------------------------
i need this because when you convert the mobile to landscape view i should be able to scroll down

**Comment by jan-supernova** [comment]
Hey badr131,
Thank you for your report! We have tried to simulate your issue, but Views with components at the same line exported properly for us and worked properly as well. Would it be possible to provide us with your project file? You can send it to me on Slack, if that suits you better. Thank you!

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey badr131,
Since the issue hasn’t been clarified for quite some time and we have not been able to simulate it in the newest version of the Supernova Studio V7.9, we are closing this ticket. If the issue still persists in the future, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!
Jan, Supernova Team
