### ISSUE TITLE
Supernova studio crashes after update

### ISSUE THREAD

**Issue by youssefsoosef** [Supernova-Studio/public-issue-tracker#138]
I was using supernova studio before updating really well, but after I updated to V7.1, if I open the sample file or try to import or open existing project, it crashes. I am using macOS HighSierra 10.13

**Comment by artufimtcev** [comment]
Hey @youssefsoosef, could you email me the project at artem@supernova.io? Thanks!

**Comment by jan-supernova** [comment]
Hey youssefsoosef,
We have not been able to simulate your issue in the newest version of the Supernova Studio. Does this issue still persist for you even after updating to the newest version V7.6 of Supernova Studio? Thank you for your answer!

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey youssefsoosef,  
Since the issue hasn’t been clarified in quite some time and we are unable to simulate this issue in the latest version of the Supernova Studio V7.9, we are closing this ticket. If you encounter this issue again or if it still persists, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!  
Jan, Supernova Team
