### ISSUE TITLE
supernova frozen when exporting to react native ( cli )

### ISSUE THREAD

**Issue by badr131** [Supernova-Studio/public-issue-tracker#142]
### Issue
> 	supernova frozen when exporting to react native ( cli )

### Context
> 	 when i export the project to react native cli supernova stop working , and i can't even close it or shutdown macOs 
 
 
### Screenshots
>  
![image](https://user-images.githubusercontent.com/52708808/63515239-0adf1580-c4f3-11e9-9cef-b1fc7da5aa64.png)

**Comment by jan-supernova** [comment]
Hey badr131,
Thank you for your report! As you informed me yesterday on Slack, the export was successful in the end although it took quite some time to finish. We have investigated this issue and there are several reasons why the React Native CLI export takes a long time. While exporting the project to React Native, there are specific operations happening in the background, which are solely dependent on React Native CLI and it is not possible for us to speed them up. Such things can be:
* Updating React Native CLI itself.
* Downloading all dependencies for the project.
* Linking all downloaded dependencies into the project.

Another reason why the export takes some time is the use of the command "react-native init" which takes longer time in general and which cannot be migrated to our own project generator yet. 

The easiest way for you how to get around this issue is using the React Native CLI export once to generate the whole project will all assets and then to use CodeX preview to test small changes in your project by copying the newly generated code from CodeX in Supernova Studio and replacing the old code in your exported project with it.
 
Also - all future React Native CLI exports should be much faster for you from now on, because the first React Native export generates a lot of necessary content in the background that is cached later on. Cached content does not have to be generated again, which speeds up future exports.

Have a wonderful day!  
Jan, Supernova Team
