### ISSUE TITLE
Show Tab Bar state doesn't save

### ISSUE THREAD

**Issue by byteasc** [Supernova-Studio/public-issue-tracker#146]
### Issue
> 	The 'Show Tab Bar' option for Screens doesn't seem to stick

### Context
> 	​If you uncheck the 'Show Tab Bar' option on a Screen then save it, then re-open the project, it will be checked again. It doesn't seem to do anything at this point in time, but it is an annoyance.

### Expected result
> 	​If I uncheck something and save it, I expect it to maintain the same state when I re-open it

### Screenshots

![image](https://user-images.githubusercontent.com/10793868/63977989-d7fcca80-ca7a-11e9-864d-d12ba3d77a90.png)

**Comment by jan-supernova** [comment]
Hey byteasc,
Thank you for your report. We have been able to successfully simulate your reported issue in the latest version of the Supernova Studio V7.3. We are now working hard on fixing this issue as fast as possible. We will let you know when the issue is resolved. Thank you again for you report.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey byteasc,
We are happy to inform you that `Show Tab Bar` state is now correctly saved in the latest version V7.7 of Supernova Studio, which was released today. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team
