### ISSUE TITLE
checkbox in application

### ISSUE THREAD

**Issue by pazhut** [Supernova-Studio/public-issue-tracker#154]
### Issue
using the provided sketch file,i would like to understand why:
- the checkbox images are not showing on the preview screen
- assuming i am exporting to flutter, how is the best way to handle the checkbox as Supernova do not have such a GUI element?

### Context
Exporting to flutter

### Expected result
checkbox images should be visible on preview and when running app

### Current result
cannot see images
[checkbox.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3633184/checkbox.zip)

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by jan-supernova** [comment]
Hey pazhut,
Thank you for your report and for your question regarding the use of the checkbox in Flutter.
* We have been able to simulate the checkbox not appearing on Preview in the current V7.6 version of the Supernova Studio. However, during our work on V7.7 version we have made some changes in Supernova Studio which addressed this issue as well. V7.7 is planned to be released very soon and we will inform you once it is released.
* When it comes to the handling of the checkbox in Flutter, then:
  * Mobile applications typically use switches instead of checkboxes, so first make sure that you really want to use a checkbox instead of a switch.
  * If you are sure about wanting to use the checkbox in your application, then you can proceed as follows: Use a regular button, which supports the state configuration. Then set the regular image of the button as the unchecked box and then set the image for the selected state to the checked box and then export the code. All you will have to do in the code is to change the state of the button when it is tapped. We hope this answer clears everything up for you.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey pazhut,
We are happy to inform you that the issue regarding checkboxes not being properly imported from the Sketch design has been resolved in the latest version of the Supernova Studio V7.8, which is available for download right now. Images are exported properly to Flutter platform now as well. Thank you again for reporting this issue!  

Have a wonderful day!
Jan, Supernova Team
