### ISSUE TITLE
Tabbing on sign-in screen doesn't change field focus

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#155]
### Environment:
macOS 10.14.6
Supernova 7.6

### Issue
Tabbing between fields on the " login with Supernova" screen

### Context
Type an email address into the Email field, press tab to jump / transfer focus to the Password field

### Expected result
Should position the cursor in the next field (eg; password)

### Current result
Highlights content in the initial field that the user is in.

### Possible fix
Click with a mouse in the required field

### Screenshots
Video attached as a .zip
[supernovaSignup.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3656762/supernovaSignup.mp4.zip)

**Comment by jan-supernova** [comment]
Hey steveharman,
Thank you for your report! We have been able to successfully simulate your issue in the latest version of the Supernova Studio V7.6 and we are now working hard on fixing it as soon as possible. We will let you know once this issue is resolved.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey steveharman,  
We are happy to let you know that your issue had been resolved in the newest version of the Supernova Studio V8.3. Thank you again for you report!

Have a wonderful day!  
Jan, Supernova Team
