### ISSUE TITLE
After Effect View component export fail (with empty tag)

### ISSUE THREAD

**Issue by ngocvu576** [Supernova-Studio/public-issue-tracker#157]
### Issue

I have made an supernova UI project using After Effect View, but on my Mac (running 10.13 MACOS), it export component After Effect  with empty tag (in .xib file)

### Context

I have create one UI with After Effects View, but when I export to iOS code, the compiler have fail with Empty Tag "< />". I have also attached project file !

### Screenshots	
<img width="360" alt="emptytag" src="https://user-images.githubusercontent.com/7045986/66729369-2ae8e080-ee75-11e9-9a22-8e20de7267b4.png">

[AfterEffectFail.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3722907/AfterEffectFail.zip)

**Comment by jan-supernova** [comment]
Hey ngocvu576,
The After Effects View component had been deprecated because our implementation of this component for all platforms didn’t turn out to be sufficient. We are now working on general improvements within Supernova Studio to make you able to natively create the same type of content that you would make with the After Effects View component. Sorry for the inconvenience.

Have a wonderful day!  
Jan, Supernova Team
