### ISSUE TITLE
too narrow for entering shadow setting values

### ISSUE THREAD

**Issue by ngocvu576** [Supernova-Studio/public-issue-tracker#170]
### Issue
> 	adding shadow of text can not see the setting values

### Screenshots
> 	​[if relevant, include a s
<img width="237" alt="Screen Shot 2019-11-15 at 14 48 53" src="https://user-images.githubusercontent.com/7045986/68926294-c1cbf400-07b7-11ea-9b79-686e0b44bc1c.png">
creenshot]

**Comment by jan-supernova** [comment]
Hey ngocvu576,
Thank you for your report! The cause of this issue is the width of the right menu not being rendered correctly. This is the issue that arrived with macOS Catalina and we are currently working on fixing it. However, it is only a visual issue - if you click into the input fields, you can still write and set values in them and they will work even though you don’t see them. However, as this is the issue that affects all macOS Catalina users, we are working hard on fixing it as quickly as possible. We will let you know when this issue is resolved.

Have a wonderful day!  
Jan, Supernova Team
