### ISSUE TITLE
Supernova unexpectedly closes on Adobe XD import

### ISSUE THREAD

**Issue by svillegas9** [Supernova-Studio/public-issue-tracker#177]
Issue
Supernova unexpectedly closes on Adobe XD import

Context
When I open supernova and import my file I select the pages and after that, it closes unexpectedly.

**Comment by jan-supernova** [comment]
Hey svillegas9!
Thank you for creating this ticket. We have been able to simulate your issue and we are now working hard on fixing it as soon as possible. I got your XD file on Slack - thank you for that as well! We will let you know immediately when your issue is resolved.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey svillegas9
We are happy to let you know that your issue was resolved in the newest version of the Supernova Studio V8.3. Your XD file is no longer causing the Supernova Studio to crash. Thank you again for reporting this issue to us!

Have a wonderful day!  
Jan, Supernova Team
