### ISSUE TITLE
 boxshadow effects are not able to conver to code. 

### ISSUE THREAD

**Issue by futuravis** [Supernova-Studio/public-issue-tracker#182]
### Issue
> Trying to give boxshadow and I can't able to achieve it.

### Context
> 	I am rendering a image and the image have a shadow effect. So I had a another image in the background and made it blurring. But while converting to code it's not working. 

### Expected result
> 	​I should be able to apply the boxshadow to a image.

### Current result
> 	I am not sure, how to achieve this?

**Comment by jan-supernova** [comment]
Hey!
Can we ask which platform are you using? Also, if the shadow is not working properly, make sure the corner radius is not applied to the component at the same time. Shadow and corner radius can't be used together - that is a known limitation of iOS in general.
If this is not the case, please inform us about which platform are you using. If you want to, you can also send us your project to support@supernova.io and we will take a look at it. Thank you for letting us know!

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey futuravis,
Since this issue hasn’t been sufficiently clarified for quite some time, we are closing this ticket. If you encounter this issue again or if it still persists, feel free to reopen this ticket or to create a new one and we will take a look at it. 

Have a wonderful day!
Jan, Supernova Team
