### ISSUE TITLE
Some of the oval shapes are not getting imported from sketch. oval that act as boundary element to a button show on the artboard but do not show on the components tab. 

### ISSUE THREAD

**Issue by harshd121** [Supernova-Studio/public-issue-tracker#187]
### Issue
> 	[Provide general introduction to the issue]

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by jan-supernova** [comment]
Hey harshd121,
Thank you for reporting this issue. Imported design should always look the same as the initial one, so that is definitely an issue we want to fix. Can you share your Sketch project with us? We will take a look at it and let you know. You can send it to support@supernova.io if you do not want to share it publicly here. 

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey harshd121,
Since this issue hasn’t been sufficiently clarified for quite some time, we are closing this ticket. If you encounter this issue again or if it still persists, feel free to reopen this ticket or to create a new one and we will take a look at it. 

Have a wonderful day!
Jan, Supernova Team
