### ISSUE TITLE
GridList View needs CrossAxisSpacing

### ISSUE THREAD

**Issue by michael4reynolds** [Supernova-Studio/public-issue-tracker#198]
Please add control to input CrossAxisSpacing on the GridListView. Currently there is only 'Cell Spacing' which only controls the MainAxisSpacing.

**Comment by jan-supernova** [comment]
Hey michael4reynolds!
That sounds like a great Feature Request! Can you send it to https://supernova.io/feature-requests ? We are regularly going through the feature requests we get from our users in order to make sure the most desired and useful feature requests find their way into the Supernova Studio.  
Thanks to the feature requests from users like you, we already have the Figma support on our roadmap, so don’t hesitate to send us any feature requests you would find useful.

Have a wonderful day!  
Jan, Supernova Team
