### ISSUE TITLE
Scroll groups not working. 

### ISSUE THREAD

**Issue by james-valladares** [Supernova-Studio/public-issue-tracker#85]
### Issue
> 	Scroll windows not working

> 	When creating a scroll group, unable to pin to bottom of screen. Scroll window only works when using a fixed height, which provides a very poor experiences when changing screen sizes to larger devices. When I pin the scroll window the to the bottom of the screen, scrolling does not work at all.

**Comment by jan-supernova** [comment]
Hey james-valladares,  
We have thoroughly attempted to simulate the reported issue in the newest version V6.10 (build 5940) of Supernova Studio and everything appears to be working correctly. We have tried every possible pin combination (including only bottom one) for scrolling group and the scrolling worked correctly for all of them. Can you let us know if the issue still persists for you in the newest version of Supernova Studio? Thank you for the answer.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey james-valladares,
Since the issue hasn’t been clarified and we are unable to simulate it in the newest version of the Supernova Studio V7.9, we are closing this ticket. If you encounter this issue again, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!
Jan, Supernova Team
